root_dir: C:/Users/Admin/Documents/Data
input_dir:
  - C:/Users/Admin/Documents/Data/Collecte STAC/2025/Sol/Planche recyclée
  - C:/Users/Admin/Documents/Data/Collecte STAC/2026/2026-01-05/Planche_Recycle_Neige
  - C:/Users/Admin/Documents/Data/Collecte STAC/2026/2026-06-29/Planche recyclee
output_dir: C:/Users/Admin/Documents/data_gt
velocities_path: C:/Users/Admin/Documents/planches/recyclee/velocities_recyclee.csv
layers_paths:
  - C:/Users/Admin/Documents/planches/recyclee/rani_recyclee.csv
  - C:/Users/Admin/Documents/planches/recyclee/core_recyclee.csv
legend_name: legend_recyclee
margin: 5
thickness: 2
alpha: 0.6
