root_dir: C:/Users/Admin/Documents/Data
input_dir:
  - C:/Users/Admin/Documents/Data/Collecte STAC/2023
  - C:/Users/Admin/Documents/Data/Collecte STAC/2025/Aerienne
  - C:/Users/Admin/Documents/Data/Collecte STAC/2025/Sol/Planche Béton
  - C:/Users/Admin/Documents/Data/Collecte STAC/2026/2026-01-05/Planche_Beton_Neige
  - C:/Users/Admin/Documents/Data/Collecte STAC/2026/2026-06-29/Planche souple - beton
output_dir: C:/Users/Admin/Documents/data_gt
velocities_path: C:/Users/Admin/Documents/planches/souple-rigide/velocities_rigide.csv
layers_paths:
  - C:/Users/Admin/Documents/planches/souple-rigide/core_rigide.csv
legend_name: legend_rigide
margin: 5
thickness: 2
alpha: 0.6
