root_dir: C:/Users/Admin/Documents/Data
input_dir:
  - C:/Users/Admin/Documents/Data/Collecte STAC/2026/2026-06-29/Planche souple - beton
output_dir: C:/Users/Admin/Documents/data_gt
velocities_path: C:/Users/Admin/Documents/planches/souple-rigide/velocities_souple.csv
layers_paths:
  - C:/Users/Admin/Documents/planches/souple-rigide/core_souple.csv
legend_name: legend_souple
margin: 5
thickness: 2
alpha: 0.6
